"""Lightweight classification helpers for shortcut demos."""

from xai_demo_suite.models.classification.habitat_shortcut import (
    BirdShapeClassifier,
    GroupMetric,
    HabitatShortcutClassifier,
    evaluate_bird_classifier,
    group_accuracy,
    predict_bird_label,
    worst_group_accuracy,
)
from xai_demo_suite.models.classification.industrial_neural import (
    FrozenResNetIndustrialProbe,
    IndustrialExplanation,
    IndustrialPrediction,
    IndustrialProbeConfig,
    industrial_accuracy,
)
from xai_demo_suite.models.classification.shortcut import (
    ClassificationResult,
    HybridShortcutClassifier,
    ShapeClassifier,
    StampShortcutClassifier,
    accuracy,
    evaluate_classifier,
    mask_region,
    predict_label,
    swap_stamp,
)
from xai_demo_suite.models.classification.waterbirds import (
    FrozenResNetWaterbirdsProbe,
    WaterbirdsExplanation,
    WaterbirdsGroupMetric,
    WaterbirdsPrediction,
    WaterbirdsProbeConfig,
    as_classification_results,
    waterbirds_accuracy,
    waterbirds_group_accuracy,
    waterbirds_worst_group_accuracy,
)

__all__ = [
    "BirdShapeClassifier",
    "ClassificationResult",
    "FrozenResNetIndustrialProbe",
    "FrozenResNetWaterbirdsProbe",
    "GroupMetric",
    "HabitatShortcutClassifier",
    "HybridShortcutClassifier",
    "IndustrialExplanation",
    "IndustrialPrediction",
    "IndustrialProbeConfig",
    "ShapeClassifier",
    "StampShortcutClassifier",
    "WaterbirdsExplanation",
    "WaterbirdsGroupMetric",
    "WaterbirdsPrediction",
    "WaterbirdsProbeConfig",
    "accuracy",
    "as_classification_results",
    "evaluate_bird_classifier",
    "evaluate_classifier",
    "group_accuracy",
    "industrial_accuracy",
    "mask_region",
    "predict_bird_label",
    "predict_label",
    "swap_stamp",
    "waterbirds_accuracy",
    "waterbirds_group_accuracy",
    "waterbirds_worst_group_accuracy",
    "worst_group_accuracy",
]
